### PR TITLE
style: replace the smartquote in Cargo.toml with a standard apostrophe

### PR DESCRIPTION
**Pull request by AliSajid**
Hi. I have this crate in a dependency and it was causing my `fix-smartquotes` precommit action to fail. May you please accept this pull request.

### CODE REVIEW

**Comment by rkuhn** [comment]
Thanks for the PR! I have nothing against merging it, but it makes me curious: why does this pop up as a problem?

(and a nitpick: this has nothing to do with “smartquotes”, I simply used a proper apostrophe instead of the ASCII straight single quote, which is not an apostrophe)

**Comment by AliSajid** [comment]
I stand corrected on the "apostrophe". :)

I have a pre-commit action that forbids a tabs, smartquotes and some other undesirable non-ASCII characters. It's helped me catch some documentation errors. That's the only motivation.

**Comment by rkuhn** [comment]
The basic principle is clear, I just have trouble understanding how the contents of this library’s `Cargo.toml` would end up in your documentation. And I’ve seen many non-ASCII characters in the documentation of some Rust crates, including the standard library. So you might be fighting a losing battle here ;-)

**Comment by rkuhn** [comment]
Anyway, I figured this library has been very stable for a while, it solves its tiny problem, so I released the result as 1.0.0.

**Comment by AliSajid** [comment]
> The basic principle is clear, I just have trouble understanding how the contents of this library’s `Cargo.toml` would end up in your documentation. And I’ve seen many non-ASCII characters in the documentation of some Rust crates, including the standard library. So you might be fighting a losing battle here ;-)

I might be. :D I use `cargo about` to generate a License summary for my crates. The JSON output collects the dependency metadata and puts it together by license. That's how the description ended up in my repo.

Apologies for misunderstanding the question, and Thank you for including this. Congratulations on the 1.0.0 release!

**Comment by rkuhn** [comment]
Ah, interesting, thanks for the explanation!

**Pull request merged**
