### PR TITLE
Implement Debug for SyncFuture and SyncStream

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by rkuhn** [comment]
No, this would break the sole purpose of this library: the Sync wrappers can _only_ provide methods that take `&mut self`, not `&self`.

**Comment by rkuhn** [comment]
Hmm, on second thought I am less certain of my argument. It would be good if you could provide the safety reasoning in the PR description.

**Comment by nox** [comment]
What? It's safe because it doesn't access the field, it just prints `SyncStream`, just like for `SyncWrapper` which already implements `Debug`. This is in now way different from the fact that all 3 types in that crate also implement `Borrow<Self>` thanks to the blanket impl in libstd.

**Comment by rkuhn** [comment]
Yes, you’re right. Sorry, I was in a different context and mixed things up.

**Comment by rkuhn** [comment]
Thanks a lot, and sorry again.

**Comment by nox** [comment]
No worries! Do you think you could make a release with this PR?

**Comment by rkuhn** [comment]
already on it

**Comment by rkuhn** [comment]
done

**Pull request merged**
