### PR TITLE
Impl Clone if T is Clone

### PR DESCRIPTION
**Pull request by banool**
This makes getting a Clone + Sync Tower Service possible, see https://github.com/hyperium/tonic/issues/1322.

### CODE REVIEW

**Comment by rkuhn** [comment]
This (“sync”) is a difficult topic, so it is difficult to be 100% certain, but I think your proposal is unsound: SyncWrapper’s only purpose is to ensure that any use of the wrapped type is guarded by static exclusion. In other words, we can only allow methods to be called that take `&mut self`. Clone is not of this shape, so allowing this would break the guarantees.

**Comment by banool** [comment]
If I'm not wrong, this is a bit of a false equivalence, because in this case the clone just completely clones both the inner T and the wrapper. So the thing that was cloned is still guarded by static exclusion right? Agreed that this is a tricky topic though so I too am not 100% sure.

**Comment by rkuhn** [comment]
Cloning will invoke `T::clone(&self.0)`, so it does run arbitrary unsynchronised code via a shared reference — which is only safe if `T: Sync`.

**Comment by rkuhn** [comment]
Cloning will invoke `T::clone(&self.0)`, so it does run arbitrary unsynchronised code via a shared reference — which is only safe if `T: Sync`.

**Comment by banool** [comment]
If that's the case would you accept this PR if I added the `Sync` bound to `T` in addition to `Clone`?

**Comment by rkuhn** [comment]
For types that already implement `Sync` there is no need to use SyncWrapper — my impression is that you are barking up the wrong tree. From the linked issue it is not clear to me what the overall issue is that we’re trying to solve here.

**Comment by banool** [comment]
Ah yes you're right. My bad, getting mixed up with lots of different issues here. Thanks for helping out 😄

**Comment by rkuhn** [comment]
You’re welcome!

**Pull request closed without merging**
